### ISSUE TITLE
Can we identify parent tab and child tab like "tabs.openerTabId" in chrome extension

### ISSUE THREAD

**Issue by Prasadraaj** [prasanaworld/SafariAppExtension-WindowTabManagement#1]
Thanks for the awesome library. This was really useful.
My question is can we identify parent and child tabs. Example i entered "Github" in search bar of safari. The page will show all inputs and links related to "Github". I treat this tab as parent tab. When we click on any one of the link/url and open that in next tab, it should be treated/considered as child tab of previous one. 

Please suggest any solution for above requirement.

**Comment by prasanaworld** [comment]
Hi @Prasadraaj, 

Glad to know that library is useful for you. 

Before heading to the problem, I would highly recommend to watch [Apple WWDC2020](https://developer.apple.com/videos/play/wwdc2020/10665/). Apple is bring back old safari web extension which support standard web extension style API. It worth waiting.

regarding openerTabId implementation, Fist of all But it's not so straight forward because apple doesn't provide any API to achieve it.

1. In the content-script JS side add an event listener for all link/button which will open a tab. 
2. Send the a `safari.extension.dispatch({ url: "url which is to be opened"})` to extension.
3. create a timer at the extension side in swift and store url and tabID of the sender.
4. Now before the timer elapses, if u get any event for page load (refer [analyzeEventMessage](https://github.com/prasanaworld/SafariAppExtension-WindowTabManagement/blob/master/WindowTabManangement%20Extension/SafariWindowTab/SafariWindowTabManager.swift#L172))
5. Now if the url matches, with high confidence we set stored tabID as openerTabID for the current tab else clear the timer.

Best of Luck.
